import { z } from 'zod'
import { idSchema, isoDateTimeSchema, periodSchema } from './api.js'
import { exportFormatSchema, localeSchema } from './enums.js'

/**
 * Reports (§44, §45, §46).
 *
 * The Monthly Financial Review is the artefact that fulfils the sellable
 * promise: upload the files, receive the monthly management review in five
 * minutes. It is what replaces the four hours a Finance Manager spends every
 * month.
 *
 * Delivered in M6 with sections generated by template — without AI. The AI
 * arrives in M7 to write the narrative of what already exists, which is an
 * addition and not a requirement.
 */

export const REPORT_SECTION_KINDS = [
  'EXECUTIVE_SUMMARY',
  'REVENUE',
  'EXPENSES',
  'PROFIT',
  'MARGIN',
  'CASH',
  'MAJOR_CHANGES',
  'RISKS',
  'OPPORTUNITIES',
  'RECOMMENDATIONS',
  'EVIDENCE',
  'APPENDIX',
] as const
export const reportSectionKindSchema = z.enum(REPORT_SECTION_KINDS)
export type ReportSectionKind = z.infer<typeof reportSectionKindSchema>

export const reportSectionSchema = z.object({
  kind: reportSectionKindSchema,
  title: z.string(),
  /** Markdown. By template in M6, written by the AI from M7 onwards. */
  body: z.string(),
  /** True when the text came out of a model — the PDF marks it. */
  aiGenerated: z.boolean(),
})
export type ReportSection = z.infer<typeof reportSectionSchema>

/**
 * Reproducibility metadata (§46).
 *
 * Without this, reprinting the July report after someone corrects a file gives
 * another number, and nobody can say which one was right. In a document that
 * goes to a bank or a board, it is the difference between a report and a draft.
 */
export const reportMetadataSchema = z.object({
  organizationId: idSchema,
  period: periodSchema,
  datasetVersion: z.number().int(),
  metricsVersion: z.string(),
  aiProvider: z.string().nullable(),
  aiModel: z.string().nullable(),
  promptVersion: z.string().nullable(),
  locale: localeSchema,
  generatedAt: isoDateTimeSchema,
  generatedByUserId: idSchema,
})
export type ReportMetadata = z.infer<typeof reportMetadataSchema>

export const reportSchema = z.object({
  id: idSchema,
  organizationId: idSchema,
  title: z.string(),
  period: periodSchema,
  sections: z.array(reportSectionSchema),
  metadata: reportMetadataSchema,
  createdAt: isoDateTimeSchema,
})
export type Report = z.infer<typeof reportSchema>

export const generateReportInputSchema = z.object({
  period: periodSchema,
  locale: localeSchema.optional(),
  /** Without AI it generates the sections by template — the M6 behaviour. */
  useAI: z.boolean().default(false),
})
export type GenerateReportInput = z.infer<typeof generateReportInputSchema>

export const exportRequestSchema = z.object({
  format: exportFormatSchema,
  locale: localeSchema.optional(),
})
export type ExportRequest = z.infer<typeof exportRequestSchema>

/**
 * Exported file.
 *
 * A signed, short-lived URL, served from outside the application's domain — a
 * financial report accessible by a permanent link would be a leak with the
 * appearance of a feature.
 */
export const exportResultSchema = z.object({
  url: z.string().url(),
  fileName: z.string(),
  expiresAt: isoDateTimeSchema,
})
export type ExportResult = z.infer<typeof exportResultSchema>
